// Package schedule holds dokploy_schedule: a cron job Dokploy runs against
// a service, a remote server, or the Dokploy host itself.
package schedule

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"

	"github.com/vanillauys/terraform-provider-dokploy/internal/client"
	"github.com/vanillauys/terraform-provider-dokploy/internal/tfutil"
)

var (
	_ resource.Resource                = (*scheduleResource)(nil)
	_ resource.ResourceWithConfigure   = (*scheduleResource)(nil)
	_ resource.ResourceWithImportState = (*scheduleResource)(nil)
)

type scheduleResource struct{ client *client.Client }

func NewResource() resource.Resource { return &scheduleResource{} }

func (r *scheduleResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_schedule"
}

func (r *scheduleResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	requiresReplace := []planmodifier.String{stringplanmodifier.RequiresReplace()}
	resp.Schema = schema.Schema{
		Description: "A cron job Dokploy runs against a service, a remote server, or the Dokploy host itself.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				Description:   "Schedule id.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"name": schema.StringAttribute{Required: true, Description: "Display name."},
			"cron_expression": schema.StringAttribute{
				Required:    true,
				Description: "Standard five-field cron expression, e.g. `0 3 * * *`. Dokploy does not validate it at write time; a malformed expression simply never fires.",
			},
			"command": schema.StringAttribute{
				Required:    true,
				Description: "Command to run.",
			},
			"schedule_type": schema.StringAttribute{
				Required: true,
				Description: "What the job runs against: `application`, `compose`, `server`, or `dokploy-server`. " +
					"`dokploy-server` runs on the Dokploy host itself and takes no `service_id`. Changing this forces replacement.",
				PlanModifiers: requiresReplace,
				Validators:    []validator.String{stringvalidator.OneOf(client.ScheduleTypes...)},
			},
			"service_id": schema.StringAttribute{
				Optional: true,
				Description: "Id of the application, compose service or server this runs against. Required for every " +
					"`schedule_type` except `dokploy-server`, which has no parent. Changing it forces replacement: " +
					"Dokploy's update endpoint sets the new parent without clearing the old one.",
				PlanModifiers: requiresReplace,
			},
			"shell_type": schema.StringAttribute{
				Optional: true, Computed: true, Default: stringdefault.StaticString("bash"),
				Description: "Shell the command runs under: `bash` or `sh`.",
				Validators:  []validator.String{stringvalidator.OneOf(client.ShellTypes...)},
			},
			"enabled": schema.BoolAttribute{
				Optional: true, Computed: true, Default: booldefault.StaticBool(true),
				Description: "Whether the job runs. Defaults to `true`: Dokploy leaves this null when a schedule is " +
					"created through the API alone, which is neither on nor off, and a schedule declared in " +
					"configuration that silently never fires is the worse failure.",
			},
			"description": schema.StringAttribute{Optional: true, Description: "Free-form description."},
			"script": schema.StringAttribute{
				Optional:    true,
				Description: "Inline script body, as an alternative to a one-line `command`.",
			},
			"timezone": schema.StringAttribute{
				Optional:    true,
				Description: "IANA timezone the cron expression is evaluated in, e.g. `Africa/Johannesburg`. Defaults to the server's timezone.",
			},
			"service_name": schema.StringAttribute{
				Optional:    true,
				Description: "Name of the specific container to run in, for compose services with more than one.",
			},
			"app_name": schema.StringAttribute{
				Computed:      true,
				Description:   "Dokploy-internal app name, generated by the server.",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"created_at": schema.StringAttribute{
				Computed:      true,
				Description:   "Creation timestamp (server-side).",
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
		},
	}
}

func (r *scheduleResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	c, diags := tfutil.ClientFromProviderData(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if c != nil {
		r.client = c
	}
}

// validateParent enforces that service_id is present for every schedule_type
// that has a parent, and absent for the one that does not.
//
// It runs in Create/Update rather than as a ConfigValidator because the rule
// is conditional on another attribute's value, which the stock config
// validators cannot express.
func validateParent(m resourceModel) error {
	hasID := !m.ServiceID.IsNull() && m.ServiceID.ValueString() != ""
	if m.ScheduleType.ValueString() == "dokploy-server" {
		if hasID {
			return fmt.Errorf(
				"`service_id` must not be set when `schedule_type` is `dokploy-server`: " +
					"that schedule runs against the Dokploy host itself and has no parent service")
		}
		return nil
	}
	if !hasID {
		return fmt.Errorf("`service_id` is required when `schedule_type` is %q",
			m.ScheduleType.ValueString())
	}
	return nil
}

func (r *scheduleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan resourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := validateParent(plan); err != nil {
		resp.Diagnostics.AddError("Invalid schedule configuration", err.Error())
		return
	}
	created, err := r.client.CreateSchedule(ctx, createRequest(plan))
	if err != nil {
		resp.Diagnostics.AddError("Creating schedule", err.Error())
		return
	}
	flatten(created, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *scheduleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state resourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	s, err := r.client.GetSchedule(ctx, state.ID.ValueString())
	if err != nil {
		if errors.Is(err, client.ErrNotFound) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Reading schedule", err.Error())
		return
	}
	flatten(s, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *scheduleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan resourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := validateParent(plan); err != nil {
		resp.Diagnostics.AddError("Invalid schedule configuration", err.Error())
		return
	}
	if err := r.client.UpdateSchedule(ctx, updateRequest(plan)); err != nil {
		resp.Diagnostics.AddError("Updating schedule", err.Error())
		return
	}
	s, err := r.client.GetSchedule(ctx, plan.ID.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Reading schedule after update", err.Error())
		return
	}
	flatten(s, &plan)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *scheduleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state resourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.DeleteSchedule(ctx, state.ID.ValueString()); err != nil && !errors.Is(err, client.ErrNotFound) {
		resp.Diagnostics.AddError("Deleting schedule", err.Error())
	}
}

func (r *scheduleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
