package application

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/resourcevalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/vanillauys/terraform-provider-dokploy/internal/client"
	"github.com/vanillauys/terraform-provider-dokploy/internal/deploy"
	"github.com/vanillauys/terraform-provider-dokploy/internal/tfutil"
)

var (
	_ resource.Resource                     = (*applicationResource)(nil)
	_ resource.ResourceWithConfigure        = (*applicationResource)(nil)
	_ resource.ResourceWithImportState      = (*applicationResource)(nil)
	_ resource.ResourceWithConfigValidators = (*applicationResource)(nil)
)

type applicationResource struct {
	client *client.Client
	waiter deploy.Waiter
}

func NewResource() resource.Resource { return &applicationResource{} }

// ConfigValidators enforces the exactly-one-of source contract at the
// resource level (spec §5.4: exactly-one-of source blocks).
func (r *applicationResource) ConfigValidators(_ context.Context) []resource.ConfigValidator {
	return []resource.ConfigValidator{
		resourcevalidator.ExactlyOneOf(
			path.MatchRoot("github"),
			path.MatchRoot("git"),
			path.MatchRoot("docker"),
		),
	}
}

func (r *applicationResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_application"
}

func (r *applicationResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs := map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:      true,
			Description:   "Application id.",
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
		"name":        schema.StringAttribute{Required: true, Description: "Display name of the application."},
		"description": schema.StringAttribute{Optional: true, Description: "Free-form description."},
		"environment_id": schema.StringAttribute{
			Required:      true,
			Description:   "Id of the environment this application lives in (see `dokploy_project.environments`).",
			PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
		},
		"app_name": schema.StringAttribute{
			Optional:      true,
			Computed:      true,
			Description:   "Dokploy-internal app name; generated by the server when omitted.",
			PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()},
		},
		"server_id": schema.StringAttribute{
			Optional:      true,
			Description:   "Remote server to run the application on. Defaults to the Dokploy host.",
			PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
		},
		"github": schema.SingleNestedAttribute{
			Optional:    true,
			Description: "GitHub App source. Exactly one of `github`, `git`, or `docker` must be set. The GitHub provider (`github_id`) is configured in Dokploy (Git > GitHub) — a documented manual prerequisite.",
			Attributes: map[string]schema.Attribute{
				"owner":      schema.StringAttribute{Required: true, Description: "Repository owner (user or org)."},
				"repository": schema.StringAttribute{Required: true, Description: "Repository name."},
				"branch":     schema.StringAttribute{Required: true, Description: "Branch to deploy."},
				"build_path": schema.StringAttribute{Optional: true, Computed: true, Default: stringdefault.StaticString("/"), Description: "Path inside the repo to build from."},
				"github_id":  schema.StringAttribute{Required: true, Description: "Id of the GitHub provider configured in Dokploy."},
			},
		},
		"git": schema.SingleNestedAttribute{
			Optional:    true,
			Description: "Custom git source (any reachable repo over https/ssh).",
			Attributes: map[string]schema.Attribute{
				"url":        schema.StringAttribute{Required: true, Description: "Clone URL."},
				"branch":     schema.StringAttribute{Required: true, Description: "Branch to deploy."},
				"build_path": schema.StringAttribute{Optional: true, Computed: true, Default: stringdefault.StaticString("/"), Description: "Path inside the repo to build from."},
				"ssh_key_id": schema.StringAttribute{Optional: true, Description: "Id of a Dokploy SSH key for private repos."},
			},
		},
		"docker": schema.SingleNestedAttribute{
			Optional:    true,
			Description: "Docker image source.",
			Attributes: map[string]schema.Attribute{
				"image":        schema.StringAttribute{Required: true, Description: "Image reference, e.g. `nginx:1.27`."},
				"username":     schema.StringAttribute{Optional: true, Description: "Registry username for private images."},
				"password":     schema.StringAttribute{Optional: true, Sensitive: true, Description: "Registry password for private images."},
				"registry_url": schema.StringAttribute{Optional: true, Description: "Registry URL for private registries."},
			},
		},
		"build": schema.SingleNestedAttribute{
			Optional: true,
			Computed: true,
			// Optional+Computed nested attributes need an explicit plan
			// modifier or the framework marks the whole object unknown on
			// every plan when config leaves it unset — an unbounded diff
			// (spec §5.6 convergence). Verified empirically: without this,
			// TestAccApplication_dockerLifecycle's post-apply plan check
			// ("the non-refresh plan was not empty") failed even though
			// nothing had changed. Mirrors the UseStateForUnknown pattern
			// already used for docker_image/app_name in the sibling
			// postgres resource.
			PlanModifiers: []planmodifier.Object{objectplanmodifier.UseStateForUnknown()},
			Description:   "Build settings; server default is nixpacks.",
			Attributes: map[string]schema.Attribute{
				"type": schema.StringAttribute{
					Required:    true,
					Description: "Build type.",
					Validators: []validator.String{
						stringvalidator.OneOf("nixpacks", "dockerfile", "heroku_buildpacks", "paketo_buildpacks", "static", "railpack"),
					},
				},
				"dockerfile":        schema.StringAttribute{Optional: true, Description: "Dockerfile path (build type `dockerfile`)."},
				"context_path":      schema.StringAttribute{Optional: true, Description: "Docker build context path."},
				"build_stage":       schema.StringAttribute{Optional: true, Description: "Target stage for multi-stage builds."},
				"publish_directory": schema.StringAttribute{Optional: true, Description: "Publish directory (build type `static`)."},
			},
		},
		"env": schema.StringAttribute{
			Optional:    true,
			Description: "Environment variables in Dokploy's native multiline `KEY=value` format. Use Terraform sensitive variables for secret values.",
		},
		"build_args": schema.StringAttribute{
			Optional:    true,
			Description: "Build-time arguments in the same multiline format.",
		},
		// status/created_at need UseStateForUnknown like id above: verified
		// empirically that a Computed (non-Optional) attribute with no plan
		// modifier is marked unknown on every plan, which by itself makes
		// Terraform propose an update-in-place with nothing else changed —
		// reproduced against a live instance as
		// TestAccApplication_dockerLifecycle's post-apply plan check
		// ("the non-refresh plan was not empty") failing on exactly these
		// two attributes and no others (spec §5.6 convergence).
		"status": schema.StringAttribute{
			Computed:      true,
			Description:   "Application status reported by Dokploy.",
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
		"created_at": schema.StringAttribute{
			Computed:      true,
			Description:   "Creation timestamp (server-side).",
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
	}
	for k, v := range tfutil.DeployAttributes() {
		attrs[k] = v
	}
	resp.Schema = schema.Schema{
		Description: "An application service in a Dokploy environment. One unified resource over Dokploy's create + save* orchestration (source, build, env are separate API calls under the hood).",
		Attributes:  attrs,
	}
}

func (r *applicationResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected provider data", fmt.Sprintf("expected *client.Client, got %T", req.ProviderData))
		return
	}
	r.client = c
}

func (r *applicationResource) persistPartial(ctx context.Context, resp *resource.CreateResponse, m resourceModel, step string, err error) {
	if m.AppName.IsUnknown() {
		m.AppName = types.StringNull()
	}
	if m.Build.IsUnknown() {
		m.Build = types.ObjectNull(buildAttrTypes)
	}
	m.Status = types.StringNull()
	m.CreatedAt = types.StringNull()
	resp.Diagnostics.Append(resp.State.Set(ctx, &m)...)
	resp.Diagnostics.AddError(
		fmt.Sprintf("Application created, but %s failed", step),
		fmt.Sprintf("application %s exists on the server; %s failed: %s. The next apply will converge.", m.ID.ValueString(), step, err),
	)
}

// saveSource pushes whichever source block is set to the matching save*
// endpoint. Returns the step label for error reporting.
func (r *applicationResource) saveSource(ctx context.Context, id string, m resourceModel) (string, error) {
	switch {
	case !m.Github.IsNull():
		var gh githubModel
		if d := m.Github.As(ctx, &gh, objectAsOptions); d.HasError() {
			return "reading the github block", fmt.Errorf("%v", d)
		}
		return "saving the github source", r.client.SaveGithubProvider(ctx, client.SaveGithubProviderRequest{
			ApplicationID: id,
			Owner:         gh.Owner.ValueString(),
			Repository:    gh.Repository.ValueString(),
			Branch:        gh.Branch.ValueString(),
			BuildPath:     gh.BuildPath.ValueString(),
			GithubID:      gh.GithubID.ValueString(),
		})
	case !m.Git.IsNull():
		var g gitModel
		if d := m.Git.As(ctx, &g, objectAsOptions); d.HasError() {
			return "reading the git block", fmt.Errorf("%v", d)
		}
		return "saving the git source", r.client.SaveGitProvider(ctx, client.SaveGitProviderRequest{
			ApplicationID:      id,
			CustomGitURL:       g.URL.ValueString(),
			CustomGitBranch:    g.Branch.ValueString(),
			CustomGitBuildPath: g.BuildPath.ValueString(),
			CustomGitSSHKeyID:  g.SSHKeyID.ValueStringPointer(),
		})
	case !m.Docker.IsNull():
		var d dockerModel
		if diag := m.Docker.As(ctx, &d, objectAsOptions); diag.HasError() {
			return "reading the docker block", fmt.Errorf("%v", diag)
		}
		return "saving the docker source", r.client.SaveDockerProvider(ctx, client.SaveDockerProviderRequest{
			ApplicationID: id,
			DockerImage:   d.Image.ValueString(),
			Username:      d.Username.ValueStringPointer(),
			Password:      d.Password.ValueStringPointer(),
			RegistryURL:   d.RegistryURL.ValueStringPointer(),
		})
	}
	return "", nil
}

func (r *applicationResource) saveBuild(ctx context.Context, id string, m resourceModel) error {
	if m.Build.IsNull() || m.Build.IsUnknown() {
		return nil
	}
	var b buildModel
	if d := m.Build.As(ctx, &b, objectAsOptions); d.HasError() {
		return fmt.Errorf("%v", d)
	}
	return r.client.SaveBuildType(ctx, client.SaveBuildTypeRequest{
		ApplicationID:     id,
		BuildType:         b.Type.ValueString(),
		Dockerfile:        b.Dockerfile.ValueStringPointer(),
		DockerContextPath: b.ContextPath.ValueStringPointer(),
		DockerBuildStage:  b.BuildStage.ValueStringPointer(),
		PublishDirectory:  b.PublishDirectory.ValueStringPointer(),
	})
}

func (r *applicationResource) fetchStatus(id string) deploy.Fetch {
	return func(ctx context.Context) (deploy.Status, string, error) {
		app, err := r.client.GetApplication(ctx, id)
		if err != nil {
			return "", "", err
		}
		depID := ""
		if ds, derr := r.client.ListDeployments(ctx, "application", id); derr == nil && len(ds) > 0 {
			depID = ds[0].DeploymentID
		}
		return deploy.Status(app.ApplicationStatus), depID, nil
	}
}

func (r *applicationResource) deployAndWait(ctx context.Context, plan *resourceModel) error {
	timeout, err := tfutil.ParseTimeout(plan.DeploymentTimeout)
	if err != nil {
		return fmt.Errorf("invalid deployment_timeout: %w", err)
	}
	if err := r.client.DeployApplication(ctx, plan.ID.ValueString()); err != nil {
		return err
	}
	return r.waiter.Wait(ctx, timeout, r.fetchStatus(plan.ID.ValueString()))
}

func (r *applicationResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan resourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	created, err := r.client.CreateApplication(ctx, client.CreateApplicationRequest{
		Name:          plan.Name.ValueString(),
		AppName:       plan.AppName.ValueString(),
		Description:   plan.Description.ValueStringPointer(),
		EnvironmentID: plan.EnvironmentID.ValueString(),
		ServerID:      plan.ServerID.ValueStringPointer(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Creating application", err.Error())
		return
	}
	plan.ID = types.StringValue(created.ApplicationID)

	if step, err := r.saveSource(ctx, created.ApplicationID, plan); err != nil {
		r.persistPartial(ctx, resp, plan, step, err)
		return
	}
	if err := r.saveBuild(ctx, created.ApplicationID, plan); err != nil {
		r.persistPartial(ctx, resp, plan, "saving build settings", err)
		return
	}
	if !plan.Env.IsNull() || !plan.BuildArgs.IsNull() {
		err := r.client.SaveApplicationEnvironment(ctx, created.ApplicationID,
			plan.Env.ValueStringPointer(), plan.BuildArgs.ValueStringPointer())
		if err != nil {
			r.persistPartial(ctx, resp, plan, "saving environment variables", err)
			return
		}
	}
	current, err := r.client.GetApplication(ctx, created.ApplicationID)
	if err != nil {
		r.persistPartial(ctx, resp, plan, "reading the application back", err)
		return
	}
	resp.Diagnostics.Append(setComputed(ctx, current, &plan)...)

	if plan.DeployOnChange.ValueBool() {
		if err := r.deployAndWait(ctx, &plan); err != nil {
			resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
			resp.Diagnostics.AddError("Deploying application", err.Error())
			return
		}
		if current, err = r.client.GetApplication(ctx, plan.ID.ValueString()); err == nil {
			resp.Diagnostics.Append(setComputed(ctx, current, &plan)...)
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *applicationResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state resourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	app, err := r.client.GetApplication(ctx, state.ID.ValueString())
	if errors.Is(err, client.ErrNotFound) {
		resp.Diagnostics.AddWarning("Application not found",
			fmt.Sprintf("application %s no longer exists; removing it from state", state.ID.ValueString()))
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Reading application", err.Error())
		return
	}
	resp.Diagnostics.Append(flatten(ctx, app, &state)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *applicationResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state resourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	plan.ID = state.ID

	if !plan.Name.Equal(state.Name) || !plan.Description.Equal(state.Description) {
		err := r.client.UpdateApplication(ctx, client.UpdateApplicationRequest{
			ApplicationID: id,
			Name:          plan.Name.ValueString(),
			Description:   plan.Description.ValueStringPointer(),
		})
		if err != nil {
			resp.Diagnostics.AddError("Updating application", err.Error())
			return
		}
	}
	sourceChanged := !plan.Github.Equal(state.Github) || !plan.Git.Equal(state.Git) || !plan.Docker.Equal(state.Docker)
	if sourceChanged {
		if step, err := r.saveSource(ctx, id, plan); err != nil {
			resp.Diagnostics.AddError("Updating application source", fmt.Sprintf("%s: %s", step, err))
			return
		}
	}
	if !plan.Build.Equal(state.Build) && !plan.Build.IsUnknown() {
		if err := r.saveBuild(ctx, id, plan); err != nil {
			resp.Diagnostics.AddError("Saving build settings", err.Error())
			return
		}
	}
	if !plan.Env.Equal(state.Env) || !plan.BuildArgs.Equal(state.BuildArgs) {
		err := r.client.SaveApplicationEnvironment(ctx, id, plan.Env.ValueStringPointer(), plan.BuildArgs.ValueStringPointer())
		if err != nil {
			resp.Diagnostics.AddError("Saving environment variables", err.Error())
			return
		}
	}
	current, err := r.client.GetApplication(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Reading application after update", err.Error())
		return
	}
	resp.Diagnostics.Append(setComputed(ctx, current, &plan)...)

	if plan.DeployOnChange.ValueBool() && deployNeeded(plan, state) {
		if err := r.deployAndWait(ctx, &plan); err != nil {
			resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
			resp.Diagnostics.AddError("Deploying application", err.Error())
			return
		}
		if current, err = r.client.GetApplication(ctx, id); err == nil {
			resp.Diagnostics.Append(setComputed(ctx, current, &plan)...)
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *applicationResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state resourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	err := r.client.DeleteApplication(ctx, state.ID.ValueString())
	if err != nil && !errors.Is(err, client.ErrNotFound) {
		resp.Diagnostics.AddError("Deleting application", err.Error())
	}
}

func (r *applicationResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
