package postgres

import (
	"context"
	"errors"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/vanillauys/terraform-provider-dokploy/internal/client"
	"github.com/vanillauys/terraform-provider-dokploy/internal/deploy"
	"github.com/vanillauys/terraform-provider-dokploy/internal/tfutil"
)

var (
	_ resource.Resource                = (*postgresResource)(nil)
	_ resource.ResourceWithConfigure   = (*postgresResource)(nil)
	_ resource.ResourceWithImportState = (*postgresResource)(nil)
)

type postgresResource struct {
	client *client.Client
	waiter deploy.Waiter
}

func NewResource() resource.Resource { return &postgresResource{} }

func (r *postgresResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_postgres"
}

func (r *postgresResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	attrs := map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Computed:      true,
			Description:   "Postgres service id.",
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
		"name": schema.StringAttribute{Required: true, Description: "Display name of the database service."},
		"environment_id": schema.StringAttribute{
			Required:      true,
			Description:   "Id of the environment this service lives in (see `dokploy_project.environments`).",
			PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
		},
		"database_name": schema.StringAttribute{
			Required:      true,
			Description:   "Name of the PostgreSQL database.",
			PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
		},
		"database_user": schema.StringAttribute{
			Required:      true,
			Description:   "PostgreSQL user.",
			PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
		},
		"database_password": schema.StringAttribute{
			Required:    true,
			Sensitive:   true,
			Description: "PostgreSQL password. Changing it triggers a redeploy.",
		},
		"docker_image": schema.StringAttribute{
			Optional:      true,
			Computed:      true,
			Description:   "Postgres docker image, e.g. `postgres:16-alpine`. Server default when omitted.",
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
		"description": schema.StringAttribute{Optional: true, Description: "Free-form description."},
		"env": schema.StringAttribute{
			Optional:    true,
			Description: "Extra environment variables in Dokploy's native multiline `KEY=value` format. Use Terraform sensitive variables for secret values.",
		},
		"external_port": schema.Int64Attribute{
			Optional:    true,
			Description: "Host port to expose PostgreSQL on. Unset keeps the database internal-only.",
		},
		"app_name": schema.StringAttribute{
			Optional:      true,
			Computed:      true,
			Description:   "Dokploy-internal app name; generated by the server when omitted.",
			PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace(), stringplanmodifier.UseStateForUnknown()},
		},
		"server_id": schema.StringAttribute{
			Optional:      true,
			Description:   "Remote server to run the service on. Defaults to the Dokploy host.",
			PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
		},
		// status deliberately has NO UseStateForUnknown: it is genuinely
		// server-mutable (a deploy moves it idle -> running -> done), so
		// pinning the prior value as a *known* plan value makes Terraform core
		// reject the apply with "Provider produced inconsistent result after
		// apply". See the long note on the same attribute in
		// internal/resources/application/resource.go.
		"status": schema.StringAttribute{Computed: true, Description: "Service status reported by Dokploy."},
		// created_at is immutable server-side, so pinning it is always safe.
		"created_at": schema.StringAttribute{
			Computed:      true,
			Description:   "Creation timestamp (server-side).",
			PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
		},
	}
	for k, v := range tfutil.DeployAttributes() {
		attrs[k] = v
	}
	resp.Schema = schema.Schema{
		Description: "A PostgreSQL database service in a Dokploy environment.",
		Attributes:  attrs,
	}
}

func (r *postgresResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	c, diags := tfutil.ClientFromProviderData(req.ProviderData)
	resp.Diagnostics.Append(diags...)
	if c != nil {
		r.client = c
	}
}

// persistPartial records what exists so far and the error; the next apply
// converges (spec §5.4). Unknown computed fields are nulled for state.
func (r *postgresResource) persistPartial(ctx context.Context, state *resource.CreateResponse, m resourceModel, step string, err error) {
	if m.DockerImage.IsUnknown() {
		m.DockerImage = types.StringNull()
	}
	if m.AppName.IsUnknown() {
		m.AppName = types.StringNull()
	}
	m.Status = types.StringNull()
	m.CreatedAt = types.StringNull()
	state.Diagnostics.Append(state.State.Set(ctx, &m)...)
	state.Diagnostics.AddError(
		fmt.Sprintf("Postgres created, but %s failed", step),
		fmt.Sprintf("service %s exists on the server; %s failed: %s. The next apply will converge.", m.ID.ValueString(), step, err),
	)
}

// fetchStatus polls GetPostgres for the applicationStatus. It does not
// consult deployment.allByType for a deployment id: verified empirically
// against a live Dokploy instance (2026-07-23) that standalone database
// services (postgres, and by the same enum, mysql/mariadb/mongo/redis) have
// no deployment-history records at all — the endpoint's `type` query
// param is a closed enum of
// application|compose|server|schedule|previewDeployment|backup|volumeBackup,
// which does not include "postgres" or any db-engine value (confirmed
// 400 Input validation failed), and neither `postgres.deployments` nor
// `deployment.byPostgresId` exist (404 Not found). Database services are
// applied via a direct docker service update rather than a tracked
// build/deploy pipeline, so there is nothing to look up here.
//
// This also means postgres cannot use the "wait until a deployment newer than
// the one that existed before the deploy call appears" gate that
// applicationResource.fetchStatus uses to avoid mistaking a stale terminal
// status for success. It does not need one: measured against the same live
// instance (v0.29.13, 2026-07-25), postgres.deploy is fully SYNCHRONOUS — the
// POST itself takes ~2s and does not return until the service has already
// reached applicationStatus "done", so the waiter's first poll is reading the
// new deploy's outcome, never the previous one's. (application.deploy by
// contrast returns in ~30ms, having committed status "running" and the new
// deployment row before responding.)
func (r *postgresResource) fetchStatus(id string) deploy.Fetch {
	return func(ctx context.Context) (deploy.Status, string, error) {
		pg, err := r.client.GetPostgres(ctx, id)
		if err != nil {
			return "", "", err
		}
		return deploy.Status(pg.ApplicationStatus), "", nil
	}
}

func (r *postgresResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan resourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	created, err := r.client.CreatePostgres(ctx, client.CreatePostgresRequest{
		Name:             plan.Name.ValueString(),
		AppName:          plan.AppName.ValueString(),
		DatabaseName:     plan.DatabaseName.ValueString(),
		DatabaseUser:     plan.DatabaseUser.ValueString(),
		DatabasePassword: plan.DatabasePassword.ValueString(),
		DockerImage:      plan.DockerImage.ValueString(),
		Description:      plan.Description.ValueStringPointer(),
		EnvironmentID:    plan.EnvironmentID.ValueString(),
		ServerID:         plan.ServerID.ValueStringPointer(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Creating postgres", err.Error())
		return
	}
	plan.ID = types.StringValue(created.PostgresID)

	if !plan.Env.IsNull() {
		// Nothing to clear on a fresh service; only save when set.
		if err := r.client.SavePostgresEnvironment(ctx, created.PostgresID, plan.Env.ValueStringPointer()); err != nil {
			r.persistPartial(ctx, resp, plan, "saving environment variables", err)
			return
		}
	}
	if !plan.ExternalPort.IsNull() {
		// Nothing to clear on a fresh service; only save when set.
		if err := r.client.SavePostgresExternalPort(ctx, created.PostgresID, plan.ExternalPort.ValueInt64Pointer()); err != nil {
			r.persistPartial(ctx, resp, plan, "saving the external port", err)
			return
		}
	}
	current, err := r.client.GetPostgres(ctx, created.PostgresID)
	if err != nil {
		r.persistPartial(ctx, resp, plan, "reading the service back", err)
		return
	}
	setComputed(current, &plan)

	if plan.DeployOnChange.ValueBool() {
		if err := r.deployAndWait(ctx, &plan); err != nil {
			resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
			resp.Diagnostics.AddError("Deploying postgres", err.Error())
			return
		}
		if current, err = r.client.GetPostgres(ctx, plan.ID.ValueString()); err == nil {
			setComputed(current, &plan)
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *postgresResource) deployAndWait(ctx context.Context, plan *resourceModel) error {
	timeout, err := tfutil.ParseTimeout(plan.DeploymentTimeout)
	if err != nil {
		return fmt.Errorf("invalid deployment_timeout: %w", err)
	}
	if err := r.client.DeployPostgres(ctx, plan.ID.ValueString()); err != nil {
		return err
	}
	return r.waiter.Wait(ctx, timeout, r.fetchStatus(plan.ID.ValueString()))
}

func (r *postgresResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state resourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	pg, err := r.client.GetPostgres(ctx, state.ID.ValueString())
	if errors.Is(err, client.ErrNotFound) {
		resp.Diagnostics.AddWarning("Postgres not found",
			fmt.Sprintf("postgres %s no longer exists; removing it from state", state.ID.ValueString()))
		resp.State.RemoveResource(ctx)
		return
	}
	if err != nil {
		resp.Diagnostics.AddError("Reading postgres", err.Error())
		return
	}
	flatten(pg, &state)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *postgresResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state resourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	id := state.ID.ValueString()
	plan.ID = state.ID

	err := r.client.UpdatePostgres(ctx, client.UpdatePostgresRequest{
		PostgresID:       id,
		Name:             plan.Name.ValueString(),
		Description:      plan.Description.ValueStringPointer(),
		DockerImage:      plan.DockerImage.ValueString(),
		DatabasePassword: plan.DatabasePassword.ValueString(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Updating postgres", err.Error())
		return
	}
	// ValueStringPointer(), not ValueString(): removing `env` from config must
	// reach the server as an explicit null so the stored value is cleared.
	// ValueString() yields "" for a null, which the server would store
	// verbatim, leaving Read to report "" against a null state forever
	// (spec §5.6). See SavePostgresEnvironment's doc comment.
	if !plan.Env.Equal(state.Env) {
		if err := r.client.SavePostgresEnvironment(ctx, id, plan.Env.ValueStringPointer()); err != nil {
			resp.Diagnostics.AddError("Saving environment variables", err.Error())
			return
		}
	}
	// No IsNull() guard here (unlike Create): removing external_port from
	// config must clear it server-side too, or state would commit null
	// while the server keeps the old port, and Read would re-populate it
	// on every subsequent plan (permanent non-convergence, spec §5.6).
	// A nil pointer marshals to JSON null, which the API accepts to clear.
	if !plan.ExternalPort.Equal(state.ExternalPort) {
		if err := r.client.SavePostgresExternalPort(ctx, id, plan.ExternalPort.ValueInt64Pointer()); err != nil {
			resp.Diagnostics.AddError("Saving the external port", err.Error())
			return
		}
	}
	current, err := r.client.GetPostgres(ctx, id)
	if err != nil {
		resp.Diagnostics.AddError("Reading postgres after update", err.Error())
		return
	}
	setComputed(current, &plan)

	if plan.DeployOnChange.ValueBool() && deployNeeded(plan, state) {
		if err := r.deployAndWait(ctx, &plan); err != nil {
			resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
			resp.Diagnostics.AddError("Deploying postgres", err.Error())
			return
		}
		if current, err = r.client.GetPostgres(ctx, id); err == nil {
			setComputed(current, &plan)
		}
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *postgresResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state resourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	err := r.client.DeletePostgres(ctx, state.ID.ValueString())
	if err != nil && !errors.Is(err, client.ErrNotFound) {
		resp.Diagnostics.AddError("Deleting postgres", err.Error())
	}
}

func (r *postgresResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
	// deploy_on_change / deployment_timeout are provider-only: there is
	// nothing server-side to read them back from, so they must be seeded with
	// their schema defaults or the plan after an import is never empty. See
	// tfutil.ImportDeployDefaults for why the framework re-applies defaults on
	// every plan, not just on create.
	resp.Diagnostics.Append(tfutil.ImportDeployDefaults(ctx, &resp.State)...)
}
